#!/usr/bin/env bash
#Bash script that pings an IP address passed as an argument
first_arguentms=$1
if [ "$first_arguentms" == "" ];
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$first_arguentms"
fi
