#!/usr/bin/env bash
#creacion de archivo que contenga su PID
#Atrapa el codigo SIGTERM y eliminalo
#Atrapa el codigo SIGINT y eliminalo
echo $$ > /var/run/myscript.pid
trap 'rm /var/run/myscript.pid; echo "I hate the kill command"; exit' SIGTERM
trap 'rm /var/run/myscript.pid; echo "Y U no love me?!"; exit' SIGINT
while true;
do
	echo "To infinity and beyond"
done
