#!/usr/bin/env bash
#Bash script that gives you information about the school file.
file=school
#exist file
if [ -e $file ]
then
	echo "school file exists"
	#empty
	if [ -s $file ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	#file is a regular
	if [ -f $file ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"	
fi	
